### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Skorfulose** [almenscorner/intunecd-monitor#18]
Hi Tobias,

first off: I appreciate your effort here! Your tool looks very much like what we currently miss in our Intune operations.

I deployed the app service using your template, set up the app registration, created the admin role and added to my user. So basically, followed your readme guide. Now I receive a 502 Bad Gateway when browsing my xxx.azurewebsites.net URL, and I don't know where to start troubleshooting. Any hint for me?

Kind regards,
Thomas

**Comment by almenscorner** [comment]
Hi,

Thank you!

Can you open the "Log Stream" on the app service and monitor it while trying to reach the site? it should give you some details about what might be going on.

**Comment by Skorfulose** [comment]
Thanks for the pointer. Found that sqlalchemy is failing the login to my SQL DB. Need to troubleshoot further...
