### ISSUE TITLE
Pipelines missing on dashboard

### ISSUE THREAD

**Issue by frost-cqre** [almenscorner/intunecd-monitor#22]
I have deployed IntuneCD Monitor on my home tenant without problems and it is working as expected. I then tried to replicate the setup on customer tenant and while it works, there is missing the top row with the pipelines on the dashboard. Otherwise it seems to be working. What could be the reason for pipelines not showing up? Some permission issue?

Thank you

**Comment by almenscorner** [comment]
Hi,

It can either be that you do not have access to that devops org and project or the pipelines has never been run in devops. Both of these can cause this behaviour

**Comment by almenscorner** [comment]
Were you able to get the pipelines to show?
