### ISSUE TITLE
info/documentation for docker deployment

### ISSUE THREAD

**Issue by hmorandell** [almenscorner/intunecd-monitor#26]
Hi Tobias

I tried to do a deploy using the docker-compose file. When firing up, I have several errors where it stated that client veriables ecc. are missing...
Do you have by chance a documentation available on howto deploy the tool using the docker compose file? That would be great!

thanks
hans

**Comment by almenscorner** [comment]
Hi - Is it for development purposes you're trying to deploy using compose instead?

If you want to run locally using compose, have a look at the dev compose file, that one contains needed variables to run locally. You then also need to create a .env file containing the necessary ENV vars like below and on top of that create the Azure SQL DB and Key Vault manually.

```env
AZDBSERVER=
AZDBNAME=
AZDBUSER=
AZDBPW=
AZDBDRIVER="{ODBC Driver 17 for SQL Server}"
SECRET_KEY='\x05\xa7 l:\xe2\xcd2\x97V\x8d\xd7\x15Ca\xbc\x8f8\xa8{'
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
AZURE_TENANT_ID=
COMPANY_NAME=
SERVER_NAME=0.0.0.0
ADMIN_ROLE=intunecd_admin
SCOPE='[]'
REDIRECT_PATH="/signin-oidc"
AZURE_VAULT_URL=
DOCUMENTATION_ACTIVE=
BEAT_DB_URI="sqlite:///db/schedule.db"
TIMEZONE=
```

**Comment by almenscorner** [comment]
Closing issue as no response since Sep 2023
