### ISSUE TITLE
IntuneCD monitor uses IntuneCD v2.0.2 with a bug in the prefix argument for backup

### ISSUE THREAD

**Issue by marvika** [almenscorner/intunecd-monitor#35]
I want to use IntuneCD monitor for backup/update across several tenants, but due to the current version of IntuneCD in IntuneCD-monitor, we cannot filter based on the prefixes we use.
This issue is fixed in IntuneCD, but not available in IntuneCD monitor.

Thanks for this awesome tool!

**Comment by almenscorner** [comment]
IntuneCD has been bumped to 2.0.7 in the latest version
