### ISSUE TITLE
Error when deploying Intuncd-monitor: {"code":"PrincipalTypeNotSupported","message":"Principals of type Application cannot validly be used in role assignments."}

### ISSUE THREAD

**Issue by danieldcn** [almenscorner/intunecd-monitor#36]
When deploying the application via the deploy button and the custom Azure template I have observed the following: 

If I'm understanding it correctly this looks like it's trying to assign the application ID to the key vault and something is failing. This doesn't seem to be causing a problem during the deployment as I am able to get load the UI. I'm wondering though if it's linked to another issue when I try to add a tenant in the IntuneCD UI. 

{"code":"PrincipalTypeNotSupported","message":"Principals of type Application cannot validly be used in role assignments."}

![image](https://github.com/almenscorner/intunecd-monitor/assets/6855453/7794771b-3dfc-42c8-a0f2-79ac7757b1b2)

**Comment by almenscorner** [comment]
This error occurs if you've entered the Object ID from the App Registration in Entra instead of the Enterprise Application Object ID during deployment. Either give your app the Key Vault administrator role on the resource group or redeploy providing the correct parameter

**Comment by danieldcn** [comment]
Using the Enterprise Application object ID instead of the App Registration did fixe the issue.
